# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Indian News Daily
email: bipin514@gmail.com
description: >
  Latest news from India
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.indianewsdaily.in" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Bipin Sasi'
bio: >
  Bipin Sasi is a seasoned journalist and a political observer from India.
  He can be reached at bipin514@gmail.com for any comments and suggestions.
author_image: "/assets/images/author.jpg"
twitter_username: editor_iinews
github_username:  nitin.sasi

# Google Analytics
analytics_id: "UA-59285359-8"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
