# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: India News Daily
email: editor@intelligentindia.in
description: 
  All Job At One Place ,Sarkari Jobs,sarkari naukri,sarkari result,sarkari result 2018, sarkari exam,job alert,job, Railway, Bank, SSC, Army Jobs, All India Jobs, States Jobs 
logo: "/images/jekyll-logo.jpg"
menu: "/assets/images/menu.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.indianewsdaily.in/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Bipin Sasi'
bio: >
  Bipin Sasi is a seasoned journalist and a political observer from India.
  He can be reached at bipin514@gmail.com for any comments and suggestions.
author_image: "/assets/images/author.jpg"
twitter_username: intelligent_ind
facebook_username: intelligentindia

# Google Analytics
analytics_id: "UA-59285359-8"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

theme: jekyll-theme-minimal

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - 404.md